### ISSUE TITLE
cupy error while training the model

### ISSUE THREAD

**Issue by btwbtm** [sniklaus/softmax-splatting#38]
Hi, when I reproduce this work, I always get
Exception ignored in: 'cupy.cuda.function.Module.__dealloc__'
Traceback (most recent call last):
File "cupy_backends/cuda/api/driver.pyx", line 253, in cupy_backends.cuda.api.driver.check_statuscupy_backends.cuda.api.driver.CUDADriver
Error: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered

Did you see this kind of error before? Any suggestions?

**Comment by sniklaus** [comment]
Looks like your training is naning out. If the following is nan or inf then the kernel will try to access out of bounds memory.

https://github.com/sniklaus/softmax-splatting/blob/ce9b0c0793a92489bfd8a40480b70a37f51c85d2/softsplat.py#L20-L21

You could use `tenMetric.clip(None, 20.0).exp()` instead of `tenMetric.exp()` in the following to avoid this, since the nan/inf probably comes from `tenMetric` being too large.

https://github.com/sniklaus/softmax-splatting/blob/ce9b0c0793a92489bfd8a40480b70a37f51c85d2/softsplat.py#L345
