### ISSUE TITLE
Save resulting image?

### ISSUE THREAD

**Issue by noobtoob4lyfe** [sniklaus/softmax-splatting#48]
Thanks for making this available to try out.
How would one modify the run.py to save the resulting warped image to a png file?  And is it possible to do this to an entire folder full of images?

**Comment by sniklaus** [comment]
It seems like you would like to specify arbitrary images as input and want to get interpolated frames. I am afraid that this repository only provides the softmax splatting operator and not our video frame interpolation pipeline that utilizes softmax splatting (since I am afraid that I am not allowed to release the implementation). My apologies.

**Comment by noobtoob4lyfe** [comment]
That's not entirely correct.  I have my own .flo file generated using flownet.  I want save the result that the current run.py produces, not simply view the result.

**Comment by sniklaus** [comment]
I am afraid that this repository only provides what is shown in the grey box below. Even if you provide the optical flow, there still is a feature pyramid extractor as well as a synthesis network that would be needed to perform our proposed approach.
![image](https://user-images.githubusercontent.com/1238034/147720737-ce0a1dd8-fb7e-40bd-885c-eac4400d4956.png)
